### ISSUE TITLE
Please add an example

### ISSUE THREAD

**Issue by besnoi** [oniietzschan/erogodic#1]
Your library is very interesting and I think it'd be awesome if you included an example! Regards

**Comment by oniietzschan** [comment]
You mean something like a `main.lua`, right? What kind of things would you like to see in an example? Like a really barebones dialogue box setup where you can proceed throught some messages and make some decisions?

**Comment by besnoi** [comment]
something like [moan.lua](https://github.com/ttxi/Moan.lua) i guess
(thanks for considering the issue worthwhile to reply, appreciate that :>)

**Comment by oniietzschan** [comment]
Check it out now. I hope it's helpful.
