### ISSUE TITLE
Reusing script

### ISSUE THREAD

**Issue by noah-eben** [oniietzschan/erogodic#2]
Works the first time around. Second time says "Script is finished" when player comes back and initiates conversation again. Love2d by the way. Something I'm doing wrong?

**Comment by oniietzschan** [comment]
Hey! Sorry for the late response, but it's been Christmas and all that so I'm sure you can understand.

It's difficult to diagnose your issue without a code example... but I'm pretty sure what you're doing wrong is holding onto the "script object" which is created when you run `Ero(yourScriptFunction)`. So basically, whenever the player talks to a given NPC, you need to rerun `Ero(yourScript)`. Or in other words, you shouldn't actually "reuse" them. Probably the easiest way of accomplishing this is creating the script object just in time whenever the player initiates a conversation.

Hope this helps, let me know if you figure it out!

**Comment by oniietzschan** [comment]
closing this for piece ov mind, feel free to reopen if you still need help though!

**Comment by noah-eben** [comment]
> Hey! Sorry for the late response, but it's been Christmas and all that so I'm sure you can understand.
> 
> It's difficult to diagnose your issue without a code example... but I'm pretty sure what you're doing wrong is holding onto the "script object" which is created when you run `Ero(yourScriptFunction)`. So basically, whenever the player talks to a given NPC, you need to rerun `Ero(yourScript)`. Or in other words, you shouldn't actually "reuse" them. Probably the easiest way of accomplishing this is creating the script object just in time whenever the player initiates a conversation.
> 
> Hope this helps, let me know if you figure it out!

I'm sorry I've taken this long to follow this up. I ended up scraping the library and using moan period but I want to try this again knowing there's a way around it. How would I create the object just in time whenever the player initiated conversation?  Or let go of the object whenever it's done being used? I know this comes down to lacking a proper understanding of Lua but I do hope it's not too trivial to consider replying. At the very least,  I would greatly appriciateappriciate some pointing in the right direction. Thank you.
